<?php
#for Job Service
define('JOB_SERVICE_ENV', '172.16.3.211:7171');
# for RPService
#for boomerang and nLogger
define('NLOGGER_ENV', 'local');
define("RP_SERVICE_ENV","172.16.3.211:5555");
define("DROPDOWNDATA_SERVICE_ENV","172.16.3.211:7917");
define("RESUME_SERVICE_MASTER","172.16.3.211:7921");
define("RESUME_SERVICE_SLAVE","172.16.3.211:7921");
define("RESUME_EDIT_SERVICE_MASTER","172.16.3.211:7922");
define("RESUME_SERVICE_TIMEOUT",1000);
define("SERVICE_VERSION",4);
define('RESUME_SERVICE_APP_ID', '107');
define("RESUME_SERVICE_SEL_SLAVE_SERVER",RESUME_SERVICE_SLAVE);
define("RESUME_SERVICE_SEL_MASTER_SERVER",RESUME_SERVICE_MASTER);
define('APPLY_APP_ID','107');
define('UNREG_APP_ID', '199');
define('SERVICE_APPID',107);
define('APPLY_HISTORY_ENV','DEV');
define('CONNECTION_TIME_OUT',2);
define('REQUEST_TIME_OUT',2);
define('DOMAIN_MANAGER_CONFIG', "/usr/local/apache-2.4.3/htdocs/ApplyGit/NitinApply/app/config/");
define("DB_CONFIG",'/var/www/html/Refermee/app/config/database/');
define('NAUKRI_CACHE_CONFIG', '/usr/local/apache-2.4.3/htdocs/ApplyGit/NitinApply/app/config/');
define("NC_REQUEST_PROVIDER",'ncSuperGlobalRequestProvider');
define('_COOKIE_DOMAIN', '.infoedge.com');
define('_Key_Old','test1');
define('_SubKey_Old','test2');
define('_Key_New','test3');
define('_SubKey_New','test4');
define('_TOUT','1800');
define('FILESTORAGE_SERVICE_ENV', 'dev');
define('FILESTORAGE_SERVICE_CONFIG', '/usr/local/apache-2.4.3/htdocs/ApplyGit/NitinApply/app/config/');
define('NC_FILEUPLOAD_SERVICE_ENV','dev');
#define('DROPDOWNDATA_SERVICE_ENV', 'DEV');
# #define('DROPDOWNDATA_SERVICE_ID','1');
define('CL_CONFIG', "/usr/local/apache-2.4.3/htdocs/ApplyGit/GarimaApply/app/config/");
define("_AUTH_SERVER_URL",'http://dev1.infoedge.com:8000/nLogin/Login.php');
define('DEFAULT_MAIL_SENDER','zend');
define('RP_APP_ID','126');
define('CSITE_APP_ID','128');
define('MNJ_REGISTER_URL','http://dev1.infoedge.com:8000/vishal/manager/RPUnregApply/web/register.php');
define('UPLOAD_CONFIG','/usr/local/apache-2.4.3/htdocs/ApplyGit/NitinApply/app/config/');
define('SMJLT_URL', 'http://dev4.infoedge.com/rajan/applyconfirmation/mynaukri/api/msngrsave_xmlapi.php');
define('ANTIWORD_PATH', '/usr/bin/antiword');
define('UPLOAD_PATH', '/tmp/CommonUpload');
define('PERL_PATH', '/usr/bin/perl');
define('DOCFRAC_PATH', '/usr/bin/docfrac');
define('DOCX2TXT_PATH', '/usr/local/docx2txt/docx2txt.pl');
define('PDF2TXT_PATH', '/usr/bin/pdftotext');
define('SM_SAVE_APPLY_URL','');
define('CREDERITY_SERVICE_HOST','172.16.3.211:6868');
define('CERTIFICATION_SERVICE_CONN_TIMEOUT','2');
define('CERTIFICATION_SERVICE_READ_TIMEOUT','2000000');
define('CERTIFICATION_SERVICE_HOST','172.16.3.211:6262');
define('CREDERITY_SERVICE_CONN_TIMEOUT','2');
define('CREDERITY_SERVICE_READ_TIMEOUT','2000000');
define("APPLY_RELEVANCE_SERVICE_API_URLS" , "http://172.16.3.164:4444/applyrelevancescore");
define("RESMAN_APP_ID",104);
define("STATIC_MAPPING_FILE_PATH","/apps/ApplyRevamp/current/src/Naukri/ApplyBundle/Resources/lib/paf/");
define("UNREG_APPLY_RELEVANCE_SERVICE_API_URLS", "http://172.16.3.164:4455/applyrelevancescoreUnreg");
define("_Key_New_AMR", "mailer_key");
define("_SubKey_New_AMR", "mailer_subkey");
define("SHOW_DEVELOPER_MESSAGE_DEV",1);
define("REST_API_ENV", "DEV");
define("NC_ENCRYPT_CONFIG","/usr/local/apache-2.4.3/htdocs/JobSearchRevamp/InterceptIntegration/app/config");
define("NC_ENC_KEY_DIR", NC_ENCRYPT_CONFIG);
define("NCREST_REFERER_URL_SUBSTR","applyapi");
define("ACM_UPLOAD_PATH", "/usr/local/apache-2.4.3/htdocs/ApplyGit/AcmBanners/dev/");
define("ACM_FILES_PATH","http://dev4.infoedge.com:8010/ApplyGit/AcmBanners/dev/");
define("JP_GET_REFERRED_BY_URL","http://dev1.infoedge.com:8000/jobpostinggaurav/API.php/pestAPI/getReferredBy?xid=");
define('MARKACTIVE_URL', 'http://dev2.infoedge.com:9000/mynaukri/web/mnjAPI.php/apiController/apiIndex/dailyupdates');
define('LOGIN_AUTH_GEN_URL','http://dev1.infoedge.com:8000/nLogin/index.php/login');
define('MARKACTIVE_ENV','DEV');
