## YAML Template.
---
referdb:
  factory: ReferPdoDatabase
  param:
    dsn:          mysql:host={localhost};port=3306;dbname=Refermee;
    username:     root
    password:     itsme
    reconnect:    true